<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>Wardx</RootNamespace>
    <AssemblyName>Wardx</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Client/**/*.cs" />
    <Compile Include="Dotnet/**/*.cs" />
    <Compile Include="Unity/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Core/Wardx.Core.csproj" />
  </ItemGroup>
</Project>
